# --- !Ups

CREATE TABLE "MENSEN" (
"ID" INTEGER NOT NULL PRIMARY KEY,
"NAME" VARCHAR NOT NULL,
"CITY" VARCHAR NOT NULL,
"ADDRESS" VARCHAR NOT NULL,
"COORDINATES" NUMBER NOT NULL
);

# --- !Downs

DROP TABLE "MENSEN";
